### ISSUE TITLE
Example not running

### ISSUE THREAD

**Issue by arbenede** [Octogonapus/RegisterMI.jl#4]
When I run the code under **Example** I am getting this error:

```
UndefVarError: FixedWidth not defined

Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:26
 [2] top-level scope
   @ In[1]:4
 [3] eval
   @ ./boot.jl:360 [inlined]
 [4] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1094

```

**Comment by arbenede** [comment]
I think I am still running FastHistogram v 0.1.0, I just installed it using the Package manager... Will update and try again...

**Comment by Octogonapus** [comment]
I ran `]activate --temp` and `]add MutualInformationImageRegistration, FastHistograms` and the example code runs fine, though I do have an ordering problem with `MAX_SHIFT`. I will address that. Make sure you are using these package versions
```
(jl_FRV2Ks) pkg> st
      Status `/tmp/jl_FRV2Ks/Project.toml`
  [06971c4e] FastHistograms v0.2.0
  [f55eb597] MutualInformationImageRegistration v0.1.2
```

**Comment by arbenede** [comment]
@Octogonapus thanks for you prompt reply! That's the problem I have, for some reason I cannot update to the latest tagged versions of `MutualInformationImageRegistration`, `FastHistograms` using the Julia Pkg manager. I even tried `Pkg.add(PackageSpec(name="MutualInformationImageRegistration", version="0.2.1"))` but it did not work. Maybe there is something you have to update on Github?

**Comment by Octogonapus** [comment]
The Pkg server may be lagging behind again. I also had a similar issue with other packages. Try forcing Pkg to use the Git repo instead:
```
ENV["JULIA_PKG_SERVER"] = ""
```

**Comment by arbenede** [comment]
Yes, that made it work. I am closing the issue, thanks again for your help!
