### ISSUE TITLE
Subpixel shift calculation

### ISSUE THREAD

**Issue by arbenede** [Octogonapus/RegisterMI.jl#6]
Looking at the code, I have the impression that you compute the integer shifts between the moving and the fixed image. I was wondering if you have any plan to extend the algorithm to the estimation of subpixel shifts.

**Comment by Octogonapus** [comment]
Your observation is correct; this package just does integer shifts. I currently don't have a plan to extend the implementation to cover subpixel shifts as well, but I'm not opposed to the idea. Another thing I looked at is extending [RegisterQD](https://github.com/HolyLab/RegisterQD.jl) with mutual information, but I felt that it would be too difficult or too time-consuming for the deadlines I had at the time, so I opted to create this package instead. It's also worth mentioning that one of the goals of this package is to be fast. I don't have any 100% fair benchmarks against RegisterQD, so I didn't include them in the readme, but it was too slow for my needs (even without subpixel registration).

**Comment by arbenede** [comment]
I see your point. I am actually developing a registration algorithm based on the NP Windows method for joint PDF and Mutual Information calculation and I can confirm that it is very slow! It would be interesting to combine the two methods, that is your algorithm to get within +/-1 pixel and NP Windows to reach sub pixel accuracy. Thanks for the feedback, I am closing the issue.
